# Generated by Django 4.1 on 2022-08-18 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=40)),
                ('author_name', models.CharField(max_length=30)),
                ('edition', models.CharField(blank=True, max_length=40, null=True)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('Branch_name', models.CharField(max_length=50)),
                ('rollno', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('fine', models.IntegerField(default=0)),
                ('book_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.add_book')),
                ('student_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.student')),
            ],
        ),
    ]
