# Generated by Django 4.1 on 2022-08-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_alter_issue_issue_date_alter_issue_submit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='id_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
